### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by liuy0421** [treangenlab/methphaser#10]
Hi there - I am applying Methphaser to a mouse dataset and ran into a minor issue. See error log below:

```
no reads aligned to chromosome MT, skipping...
no reads aligned to chromosome JH584301.1, skipping...
Traceback (most recent call last):
  File "/data/liuy45/conda/envs/methphaser/bin/meth_phaser_parallel", line 283, in <module>
    main(sys.argv[1:])
  File "/data/liuy45/conda/envs/methphaser/bin/meth_phaser_parallel", line 252, in main
    skipping_pair_start_list.append(phased_block_distance_list_sorted[0][0])
IndexError: list index out of range
```

Seems like `chr_block_num` is not zero, but somehow `phased_block_distance_dict` is empty? What could the problem be? Thank you so much!

**Comment by liuy0421** [comment]
Something along the lines of the following:

```
meth_phaser_parallel \
-b haplotagged.bam \
-r Mus_musculus.GRCm39.dna.primary_assembly.fa \
-g phased.gtf \
-vc output.phased.vcf \
-o output/ \
-t $SLURM_CPUS_PER_TASK
```

I did not get errors for the autosomes, sex chromosomes, and 3 other unlocalized genomic contigs.

**Comment by Fu-Yilei** [comment]
Sorry, I have 0 knowledge about mouse datasets, but I would recommend only using MethPhaser on autosomes since random x inactivation. If you could give me more information on your dataset I might be able to look into it further. Additional helpful information could be reads, vcf, etc.. However, I recommend only using it on autosomes.

**Comment by liuy0421** [comment]
Makes sense - thanks a lot!

**Comment by Mar10L** [comment]
Hi.
I am getting the same error:
```
Traceback (most recent call last):
  File "/iga/scripts/dev_modules/mambaforge/envs/duet-v0.6/bin/methphasing", line 1471, in <module>
    main(sys.argv[1:])
  File "/iga/scripts/dev_modules/mambaforge/envs/duet-v0.6/bin/methphasing", line 1396, in main
    [0], phased_region_list[1][0])]
IndexError: list index out of range
```

The command that I used was this one:
```
meth_phaser_parallel -t 10 -ml -2 \
-o methphaser \
-b grapevine.minimap2.filtered_only_primary.bam \
-r reference.fasta \
-g grapevine_phased.whatshap.stats.gtf \
-vc grapevine.clair3.phased.vcf.gz
```

Theoretically, I should not have problems with sex chromosomes, given the fact that grapevines do not possess them.

Thank you in advance for the help.
