### ISSUE TITLE
some block have only one SNP

### ISSUE THREAD

**Issue by ZON-ZONG-MIN** [treangenlab/methphaser#15]
Hi, I am using ONT R10.4.1 provided by giab ( https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/NA12878_HG001/latest/ ) and testing with whatshap.
Here are the commands I used.
```
whatshap --version
2.0
```
```
whatshap phase --ignore-read-groups --indels \
-r GCA_000001405.15_GRCh38_no_alt_analysis_set.fa \
hg001.wf_snp.vcf.gz \
hg001.sup.60x.bam \
-o whatshap_hg001_60x.vcf
bgzip -c whatshap_hg001_60x.vcf > whatshap_hg001_60x.vcf.gz
tabix -p vcf whatshap_hg001_60x.vcf.gz
whatshap haplotag --ignore-read-groups  \
whatshap_hg001_60x.vcf.gz hg001.sup.60x.bam \
-r GCA_000001405.15_GRCh38_no_alt_analysis_set.fa \
-o hg001.sup.60x.whatshap.haplotag.bam
```
```
samtools index -@ 24 hg001.sup.60x.whatshap.haplotag.bam
whatshap stats --gtf whatshap_hg001_60x.gtf whatshap_hg001_60x.vcf.gz
```
```
samtools view -bF 2304 -o hg001.sup.60x.whatshap.haplotag.bam
samtools index -@ 24 .hg001.sup.60x.whatshap.haplotag.primary.bam
```
```
meth_phaser_parallel -b hg001.sup.60x.whatshap.haplotag.primary.bam\ 
-r GCA_000001405.15_GRCh38_no_alt_analysis_set.fa\
 -g whatshap_hg001_60x.gtf -vc whatshap_hg001_60x.vcf.gz\
 -o work\

meth_phaser_post_processing -ib hg001.sup.60x.whatshap.haplotag.primary.bam -if work -ov output.vcf -ob output_ob -vc /whatshap_hg001_60x.vcf.gz -t 8

bcftools sort -Ov output.vcf -o output_sorted.vcf
```
I found that there are duplicate positions in the output vcf file.
<img width="832" alt="1690752181307" src="https://github.com/treangenlab/methphaser/assets/68158732/85388de9-cdbe-4028-92b7-607082247915">

Also, some blocks have only one SNP , I'm not sure if these are normal?

If I want to evaluate methphaser (wrong switch, N50), should I make any corrections to the output vcf file?

thank you

**Comment by Fu-Yilei** [comment]
duplicates are minor bugs and I am fixing that issue, please remove those duplicates. Also, I recommend not using MethPhaser on sex chromosomes because of random X inactivation. There could be situations where blocks only contain one SNP. MethPhaser only enhances previous SNV-based phasing, and if there is only 1 SNP in the block, that seems to be whatshap's output only contains 1 SNP, and MethPhaser cannot improve anything on that.
