### ISSUE TITLE
Question on secondary and supplementary reads

### ISSUE THREAD

**Issue by andosl** [treangenlab/methphaser#19]
It is necessary to exclude secondary and supplementary alignments with "samtools view -bF 2304 -o output.bam input.bam" before running methphaser. However, the secondary and supplementary reads could provide increased depth when assembling the haplotypes after phasing. I guess I can filter out secondary and supplementary reads that are already phased using whatsapp, and re-add them to the new bam file after methphasing?

**Comment by Fu-Yilei** [comment]
usually using supplementary and secondary alignment can cause methylation reading errors.

**Comment by andosl** [comment]
Yep, I agree. But my point is about re-introducing those reads AFTER running methphaser before assembling.

**Comment by Fu-Yilei** [comment]
I would advise not to do that because MethPhaser flip the phaseblocks and flip the reads' haplotype assignments when it finds the relation between two neighbor phaseblocks are flipped. i.e., HP1 in phaseblock 1 is the same to HP2 in phaseblock2. Reintroducing those reads might be not optimal.

**Comment by andosl** [comment]
Thanks for explaining, I see your point!
