### ISSUE TITLE
No improved phasing 

### ISSUE THREAD

**Issue by JesseBNL** [treangenlab/methphaser#23]
Hi,

We are trying to phase a region, but there remains a gap which cannot be phased using SNPs. Now we have tried the high-accuracy and high-success parameters of MethPhaser, but still we are unable to close the unphased gap. For this assembly we have methylation-called HiFi reads (N50 = 14kb) and ONT reads (N50 = 45kb) combined. 

<img width="1220" alt="Scherm­afbeelding 2024-08-06 om 11 21 49" src="https://github.com/user-attachments/assets/6c2f97f1-893b-4727-9987-3edcbf238fbb">

We suspect that one haplotype probably has an insertion at this position on one haplotype, which is absent on the other haplotype. Are there other parameters in MethPhaser, for example lowering the required coverage, to phase this difficult region? Could lowering or increasing the -c and -a parameters help?

This is our command:
`meth_phaser_parallel -b haplotagged_pri_sorted.bam -r collapsed_EAW_IGK.fa -g whatshap_phase.gtf -vc phased_whatshap_sorted.vcf.gz -o methphaser_output -ml -2`

and 

`meth_phaser_post_processing -ib haplotagged_pri_sorted.bam -if methphaser_output/ -ov methphase_whatshap_out_hs.vcf -ob methphase_whatshap_hs -vc phased_whatshap_sorted.vcf.gz -hs`

With or without the `-hs` flag.

Hopefully you can hulp us to solve this phasing problem.

**Comment by Fu-Yilei** [comment]
I think yes lowering -c and -a could be helpful, but this is a 100kb gap, is this in centromere region? might be too long for MethPhaser. However, happy to talk more if you need help.

**Comment by JesseBNL** [comment]
Lowering -c and -a did not affect the phasing unfortunately. Any other suggestions?
It is not a centromere region, but a sequence more similar to the HLA region. So we are aware that phasing is difficult, but we hoped to solve it with this tool.

**Comment by JesseBNL** [comment]
I indeed also have the image with the haplotypes colored. And it clearly shows a grey area in the gap location. 

We can do population phasing as well, but we only have a parent/child couple, which means we lack a parent for trio-binning. Do you have any suggestion that would be able to phase using a duo?

**Comment by Fu-Yilei** [comment]
My intuitive hunch of this is that you can use child sample twice as one of the parent so that you can do trio phasing. Or you can try https://odelaneau.github.io/shapeit5/
