### ISSUE TITLE
Error when running meth_phaser_parallel

### ISSUE THREAD

**Issue by sujunhao** [treangenlab/methphaser#7]
Hi,

I tried to run the example cmd of:
```
    ./meth_phaser_parallel -b test_data/HLA.R10.haplotagged.bam -r test_data/GCA_000001405.15_GRCh38_no_alt_analysis_set.chr6.fna -g test_data/LSK.filtered.gtf -vc test_data/HLA.R10.phased.vcf.gz  -o test_data/work -k -1 -ml -2
```

it raises an error of 
`File "/home/_env/anaconda3/envs/mp_env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'methphasing'`

any clue to fix it? thanks.

**Comment by Fu-Yilei** [comment]
Please put the executable `methphasing` into bashrc for `meth_phaser_parallel` to call it. exact command: export "PATH=/path/to/methphaser/:$PATH"

Thanks for noticing, I will put MethPhaser to conda for easier usage.

**Comment by sujunhao** [comment]
Got it, many thanks.
